[package]
name = "mprocs"
version = "0.2.0"
edition = "2021"

[profile.release]
strip = "symbols"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mprocs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.1.8", features = ["derive"] }
crossterm = { version = "0.20", features = ["event-stream"] }
flexi_logger = "0.22.3"
futures = { version = "*" }
indexmap = { version = "1.8.0", features = ["serde"] }
libc = "0.2.120"
log = "0.4.14"
portable-pty = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order"] }
tokio = { version = "1", features = ["full"] }
tui = { version = "*", default-features = false, features = ['crossterm'] }
unicode-width = "0.1.9"
vt100 = "0.15.1"
