[profile.release]
strip = "symbols"
opt-level = "z"   # optimize for binary size
lto = true        # link time optimization
panic = "abort"
codegen-units = 1

[workspace]
members = [
  "src",
  "vendor/pty",
  "vendor/vt100",
]
